/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserService } from "../user.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserCreateInput } from "./UserCreateInput";
import { UserWhereInput } from "./UserWhereInput";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserUpdateInput } from "./UserUpdateInput";
import { User } from "./User";
import { UserAuthenticationStrategyFindManyArgs } from "../../userAuthenticationStrategy/base/UserAuthenticationStrategyFindManyArgs";
import { UserAuthenticationStrategy } from "../../userAuthenticationStrategy/base/UserAuthenticationStrategy";
import { UserAuthenticationStrategyWhereUniqueInput } from "../../userAuthenticationStrategy/base/UserAuthenticationStrategyWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserControllerBase {
  constructor(
    protected readonly service: UserService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        email: true,
        failedLoginAttempt: true,
        failedLoginTime: true,
        firstName: true,
        id: true,
        isActive: true,
        isLocked: true,
        isRemoved: true,
        lastName: true,
        phone: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(UserFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        email: true,
        failedLoginAttempt: true,
        failedLoginTime: true,
        firstName: true,
        id: true,
        isActive: true,
        isLocked: true,
        isRemoved: true,
        lastName: true,
        phone: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        email: true,
        failedLoginAttempt: true,
        failedLoginTime: true,
        firstName: true,
        id: true,
        isActive: true,
        isLocked: true,
        isRemoved: true,
        lastName: true,
        phone: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          failedLoginAttempt: true,
          failedLoginTime: true,
          firstName: true,
          id: true,
          isActive: true,
          isLocked: true,
          isRemoved: true,
          lastName: true,
          phone: true,
          roles: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "User",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          email: true,
          failedLoginAttempt: true,
          failedLoginTime: true,
          firstName: true,
          id: true,
          isActive: true,
          isLocked: true,
          isRemoved: true,
          lastName: true,
          phone: true,
          roles: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "UserAuthenticationStrategy",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/userAuthenticationStrategies")
  @ApiNestedQuery(UserAuthenticationStrategyFindManyArgs)
  async findManyUserAuthenticationStrategies(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<UserAuthenticationStrategy[]> {
    const query = plainToClass(
      UserAuthenticationStrategyFindManyArgs,
      request.query
    );
    const results = await this.service.findUserAuthenticationStrategies(
      params.id,
      {
        ...query,
        select: {
          authenticationStrategy: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          expiresWithin: true,
          externalIdentifier: true,
          id: true,
          isActive: true,
          isRemoved: true,
          passwordHash: true,
          passwordResetToken: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          verificationToken: true,
        },
      }
    );
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/userAuthenticationStrategies")
  async connectUserAuthenticationStrategies(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserAuthenticationStrategyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userAuthenticationStrategies: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/userAuthenticationStrategies")
  async updateUserAuthenticationStrategies(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserAuthenticationStrategyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userAuthenticationStrategies: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "User",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/userAuthenticationStrategies")
  async disconnectUserAuthenticationStrategies(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: UserAuthenticationStrategyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userAuthenticationStrategies: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
