/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AuthenticationStrategyService } from "../authenticationStrategy.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AuthenticationStrategyCreateInput } from "./AuthenticationStrategyCreateInput";
import { AuthenticationStrategyWhereInput } from "./AuthenticationStrategyWhereInput";
import { AuthenticationStrategyWhereUniqueInput } from "./AuthenticationStrategyWhereUniqueInput";
import { AuthenticationStrategyFindManyArgs } from "./AuthenticationStrategyFindManyArgs";
import { AuthenticationStrategyUpdateInput } from "./AuthenticationStrategyUpdateInput";
import { AuthenticationStrategy } from "./AuthenticationStrategy";
import { UserAuthenticationStrategyFindManyArgs } from "../../userAuthenticationStrategy/base/UserAuthenticationStrategyFindManyArgs";
import { UserAuthenticationStrategy } from "../../userAuthenticationStrategy/base/UserAuthenticationStrategy";
import { UserAuthenticationStrategyWhereUniqueInput } from "../../userAuthenticationStrategy/base/UserAuthenticationStrategyWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AuthenticationStrategyControllerBase {
  constructor(
    protected readonly service: AuthenticationStrategyService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "AuthenticationStrategy",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AuthenticationStrategy })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: AuthenticationStrategyCreateInput
  ): Promise<AuthenticationStrategy> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        isActive: true,
        isRemoved: true,
        provider: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "AuthenticationStrategy",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [AuthenticationStrategy] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(AuthenticationStrategyFindManyArgs)
  async findMany(
    @common.Req() request: Request
  ): Promise<AuthenticationStrategy[]> {
    const args = plainToClass(
      AuthenticationStrategyFindManyArgs,
      request.query
    );
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        isActive: true,
        isRemoved: true,
        provider: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "AuthenticationStrategy",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AuthenticationStrategy })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: AuthenticationStrategyWhereUniqueInput
  ): Promise<AuthenticationStrategy | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        isActive: true,
        isRemoved: true,
        provider: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "AuthenticationStrategy",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AuthenticationStrategy })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: AuthenticationStrategyWhereUniqueInput,
    @common.Body() data: AuthenticationStrategyUpdateInput
  ): Promise<AuthenticationStrategy | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          isActive: true,
          isRemoved: true,
          provider: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "AuthenticationStrategy",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AuthenticationStrategy })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: AuthenticationStrategyWhereUniqueInput
  ): Promise<AuthenticationStrategy | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          isActive: true,
          isRemoved: true,
          provider: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "UserAuthenticationStrategy",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/userAuthenticationStrategies")
  @ApiNestedQuery(UserAuthenticationStrategyFindManyArgs)
  async findManyUserAuthenticationStrategies(
    @common.Req() request: Request,
    @common.Param() params: AuthenticationStrategyWhereUniqueInput
  ): Promise<UserAuthenticationStrategy[]> {
    const query = plainToClass(
      UserAuthenticationStrategyFindManyArgs,
      request.query
    );
    const results = await this.service.findUserAuthenticationStrategies(
      params.id,
      {
        ...query,
        select: {
          authenticationStrategy: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          expiresWithin: true,
          externalIdentifier: true,
          id: true,
          isActive: true,
          isRemoved: true,
          passwordHash: true,
          passwordResetToken: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          verificationToken: true,
        },
      }
    );
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "AuthenticationStrategy",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/userAuthenticationStrategies")
  async connectUserAuthenticationStrategies(
    @common.Param() params: AuthenticationStrategyWhereUniqueInput,
    @common.Body() body: UserAuthenticationStrategyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userAuthenticationStrategies: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "AuthenticationStrategy",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/userAuthenticationStrategies")
  async updateUserAuthenticationStrategies(
    @common.Param() params: AuthenticationStrategyWhereUniqueInput,
    @common.Body() body: UserAuthenticationStrategyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userAuthenticationStrategies: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "AuthenticationStrategy",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/userAuthenticationStrategies")
  async disconnectUserAuthenticationStrategies(
    @common.Param() params: AuthenticationStrategyWhereUniqueInput,
    @common.Body() body: UserAuthenticationStrategyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      userAuthenticationStrategies: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
