/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserAuthenticationStrategyService } from "../userAuthenticationStrategy.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserAuthenticationStrategyCreateInput } from "./UserAuthenticationStrategyCreateInput";
import { UserAuthenticationStrategyWhereInput } from "./UserAuthenticationStrategyWhereInput";
import { UserAuthenticationStrategyWhereUniqueInput } from "./UserAuthenticationStrategyWhereUniqueInput";
import { UserAuthenticationStrategyFindManyArgs } from "./UserAuthenticationStrategyFindManyArgs";
import { UserAuthenticationStrategyUpdateInput } from "./UserAuthenticationStrategyUpdateInput";
import { UserAuthenticationStrategy } from "./UserAuthenticationStrategy";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserAuthenticationStrategyControllerBase {
  constructor(
    protected readonly service: UserAuthenticationStrategyService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "UserAuthenticationStrategy",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserAuthenticationStrategy })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: UserAuthenticationStrategyCreateInput
  ): Promise<UserAuthenticationStrategy> {
    return await this.service.create({
      data: {
        ...data,

        authenticationStrategy: data.authenticationStrategy
          ? {
              connect: data.authenticationStrategy,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        authenticationStrategy: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        expiresWithin: true,
        externalIdentifier: true,
        id: true,
        isActive: true,
        isRemoved: true,
        passwordHash: true,
        passwordResetToken: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        verificationToken: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "UserAuthenticationStrategy",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [UserAuthenticationStrategy] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(UserAuthenticationStrategyFindManyArgs)
  async findMany(
    @common.Req() request: Request
  ): Promise<UserAuthenticationStrategy[]> {
    const args = plainToClass(
      UserAuthenticationStrategyFindManyArgs,
      request.query
    );
    return this.service.findMany({
      ...args,
      select: {
        authenticationStrategy: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        expiresWithin: true,
        externalIdentifier: true,
        id: true,
        isActive: true,
        isRemoved: true,
        passwordHash: true,
        passwordResetToken: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        verificationToken: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "UserAuthenticationStrategy",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserAuthenticationStrategy })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: UserAuthenticationStrategyWhereUniqueInput
  ): Promise<UserAuthenticationStrategy | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        authenticationStrategy: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        expiresWithin: true,
        externalIdentifier: true,
        id: true,
        isActive: true,
        isRemoved: true,
        passwordHash: true,
        passwordResetToken: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        verificationToken: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "UserAuthenticationStrategy",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserAuthenticationStrategy })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: UserAuthenticationStrategyWhereUniqueInput,
    @common.Body() data: UserAuthenticationStrategyUpdateInput
  ): Promise<UserAuthenticationStrategy | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          authenticationStrategy: data.authenticationStrategy
            ? {
                connect: data.authenticationStrategy,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          authenticationStrategy: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          expiresWithin: true,
          externalIdentifier: true,
          id: true,
          isActive: true,
          isRemoved: true,
          passwordHash: true,
          passwordResetToken: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          verificationToken: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "UserAuthenticationStrategy",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserAuthenticationStrategy })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: UserAuthenticationStrategyWhereUniqueInput
  ): Promise<UserAuthenticationStrategy | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          authenticationStrategy: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          expiresWithin: true,
          externalIdentifier: true,
          id: true,
          isActive: true,
          isRemoved: true,
          passwordHash: true,
          passwordResetToken: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          verificationToken: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
